name: Publish package to the Maven Central Repository

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8
      - name: Publish package
        run: |
          ./gradlew assemble publishToMavenLocal publish -PorchidEnvironment=prod -Prelease -Pversion=$PROJECT_VERSION
          ./gradlew publishPlugins -b buildSrc/orchidPlugin/build.gradle.kts -PorchidEnvironment=prod -Prelease -Pversion=$PROJECT_VERSION
        env:
          MAVEN_USERNAME: ${{secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{secrets.OSSRH_TOKEN }}
          PROJECT_VERSION: ${{ github.event.release.tag_name }}
      - name: Publish maven
        run: |
          cd buildSrc/orchidMavenPlugin
          ./mvnw versions:set -DnewVersion=$PROJECT_VERSION
          ./mvnw deploy
        env:
          MAVEN_USERNAME: ${{secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{secrets.OSSRH_TOKEN }}
          PROJECT_VERSION: ${{ github.event.release.tag_name }}
