name: Publish package to the Maven Central Repository

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish package
        run: |
          ./gradlew assemble publishToMavenLocal publish -PorchidEnvironment=prod -Prelease -Pversion=$PROJECT_VERSION
          ./gradlew publish -b buildSrc/orchidPlugin/build.gradle.kts -PorchidEnvironment=prod -Prelease -Pversion=$PROJECT_VERSION
        env:
          MAVEN_USERNAME: ${{secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{secrets.OSSRH_TOKEN }}
          PROJECT_VERSION: ${{ github.event.release.tag_name }}
      - name: Build docs
        run: ./gradlew assemble :docs:orchidBuild -PorchidEnvironment=prod -Prelease -Pversion=$PROJECT_VERSION
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: docs/build/docs/orchid
      - name: Publish maven
        run: |
          cd buildSrc/orchidMavenPlugin
          ./mvnw versions:set -DnewVersion=$PROJECT_VERSION
          ./mvnw --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{secrets.OSSRH_TOKEN }}
          PROJECT_VERSION: ${{ github.event.release.tag_name }}
